### ISSUE TITLE
Feature Request: Add amount of vessels to be inserted into stations.

### ISSUE THREAD

**Issue by JamieRCHI** [Gimbalhawk/DSP-Mods#1]
Would be nice if I could set the amount. In the early game, I may only want 1 or 2 of the Intersteller ships, and maybe only 5 or 10 of the Planetary drones. Thank you.

**Comment by Gimbalhawk** [comment]
That's a good idea and super easy to implement. Version 1.2.0 should be available now

**Comment by JamieRCHI** [comment]
Thank you.
