### ISSUE TITLE
Todays Patch (11/01/24) Seems to have caused Issue..

### ISSUE THREAD

**Issue by WelshGuyX** [Gimbalhawk/DSP-Mods#10]
Getting a crash from this mod since today patch...

![image](https://github.com/Gimbalhawk/DSP-Mods/assets/114473098/e128feae-771e-4c5d-bc8a-f2fdb0d273d8)

**Comment by Gimbalhawk** [comment]
Ah, looks like the issue is caused by creating at least one logistics station, then quitting back to the main menu, then loading a game and creating another logistics station. I was caching some data that was invalidated when you quit. I just uploaded a new version that should fix it.

**Comment by WelshGuyX** [comment]
Thank you... much appreciated.
