### ISSUE TITLE
REQUEST: Have ability to easily toggle on/off AutoLogisticsDroneSetup

### ISSUE THREAD

**Issue by scwagner** [Gimbalhawk/DSP-Mods#2]
There are times when I want to set up certain types of builds (like storage "modules") and I do **not** want to have any drones inserted into the PLS or ILS when setting them down.

This can be a problem when using a blueprint that has requests and demands already set inside of it for the stations, because as soon as they get put down then the auto-placed drones start running off.

**Comment by Gimbalhawk** [comment]
I thought about doing something similar at one point got lazy. Maybe I'll take another look and see if I can figure out how to do it, because it's a good idea

**Comment by Gimbalhawk** [comment]
I added an in-game config menu that lets you turn off adding drones for ILS or PLS on the go
