### ISSUE TITLE
Add-in not functional

### ISSUE THREAD

**Issue by Wolphin5** [Gimbalhawk/DSP-Mods#3]
I am not getting any errors that I can see, but I am not getting any drones or vessels auto-assigned to the logistics centres when I place them.

Game version: 0.8.22.9331 
Plug-in version: 1.4.0

I have tried removing and reloading the addon, without success.  Is there anything further I should try to resolve it?

**Comment by Gimbalhawk** [comment]
Do you have any drones in your inventory or in storage on the planet? Have you changed your config at all?

**Comment by Wolphin5** [comment]
I have 200 drones and 50 vessels in my inventory.  I have tried adjusting the config to 50 and 10, but only tosay, and had seen the error for a while before.

**Comment by Gimbalhawk** [comment]
Has it worked at all since you downloaded the mod? Can you upload the BepInEx log file? It's located at < Game Installation Directory >/Dyson Sphere Program/BeInEx/LogOutput.log

**Comment by Wolphin5** [comment]
It had been working.  It has been in the last week or so that it stopped working (hadn't realised it right away, just when I was checking why some logistic centres were not moving materials.

Log is attached.
[LogOutput.log](https://github.com/Gimbalhawk/DSP-Mods/files/7517699/LogOutput.log)

**Comment by Gimbalhawk** [comment]
AutoLogisticsDroneSetup should log a message when it loads, but I don't see it in your log. Is it enabled in your mod manager?

**Comment by Wolphin5** [comment]
Yes it is enabled.  I'll look into it at my end tomorrow.

**Comment by Wolphin5** [comment]
I uninstalled it, made sure the files were gone, redownloaded it, and when launching it appears to be working.  
Confirmed the log now has the line `[Info   :   BepInEx] Loading [AutoShuttleSetup 1.4.0]` in it.  Tested with placing a logistics centre, and had the facility come up correctly.

Thanks for the help.

**Comment by Gimbalhawk** [comment]
Weird, but I'm glad it's working now
