### ISSUE TITLE
Logistic Slot

### ISSUE THREAD

**Issue by Shorrrt** [Gimbalhawk/DSP-Mods#8]
Although not a bug, would it be possible to pull bots/drones/vessels from logistic slots? Mainly asking because of the option in DeliverySlotsTweaks by starfi5h to automatically store items there.

**Comment by Gimbalhawk** [comment]
I just made a change for some other things that should also make this work the way you want. I don't use DeliverySlotTweaks so I haven't tested that case specifically, but it should be able to pull items out of logistics storage
